AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  Static build of Pandoc for Amazon Linux 2

  Check out https://github.com/serverlesspub/pandoc-aws-lambda-binary
  for more information.
Resources:
  PandocLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: pandoc 
      Description: Static build of Pandoc for Amazon Linux 2
      ContentUri: result/
      CompatibleRuntimes:
        - nodejs10.x
      LicenseInfo: https://github.com/jgm/pandoc/blob/master/COPYRIGHT
      RetentionPolicy: Retain

Outputs:
  LayerVersion:
    Description: Layer ARN Reference
    Value: !Ref PandocLayer

Metadata:
  AWS::ServerlessRepo::Application:
    Name: pandoc-lambda-layer
    Description: >
      Static build of Pandoc for Amazon Linux 2,
      packaged as a Lambda layer. Bundles Pandoc 2.7.2.
    Author: Gojko Adzic
    SpdxLicenseId: GPL-2.0
    LicenseUrl: LICENSE.txt
    ReadmeUrl: README-SAR.md 
    Labels: ['layer', 'image', 'lambda', 'pandoc']
    HomePageUrl: https://github.com/serverlesspub/pandoc-aws-lambda-binary
    SemanticVersion: 1.0.0
    SourceCodeUrl: https://github.com/serverlesspub/pandoc-aws-lambda-binary
